@api_HostAddress = https://localhost:7041

GET {{api_HostAddress}}/
Accept: application/json
###

GET {{api_HostAddress}}/api/stocks
Accept: application/json

###

GET {{api_HostAddress}}/api/stocks/2
Accept: applicaton/json

###

POST {{api_HostAddress}}/api/stocks
Content-Type: application/json
{
  "id": 23,
  "symbol": "TST",
  "companyName": "Test Stock",
  "price": 100.0,
  "lastDiv": 0,
  "industry": "Test Industry",
  "marketCap": 1000001
}
###

PUT {{api_HostAddress}}/api/stocks/5
Content-Type: application/json
{
  "id": 23,
  "symbol": "TST",
  "companyName": "Test Stock",
  "price": 100.0,
  "lastDiv": 0,
  "industry": "Test Industry",
  "marketCap": 1000001
}